rstring: "r\"" regex* "\""

?regex: character | word | group | pipe | class | plus_quant | star_quant | num_quant

character: LETTER | NUMBER
word: WORD
group: "("regex")"
pipe: regex "|" regex
range: LETTER"-"LETTER | NUMBER"-"NUMBER
class: "["(character*range*)+"]"
?base: character | group | class
plus_quant: base"+"
star_quant: base"*"
num_quant: base"{"NUMBER"}" | base"{"NUMBER","NUMBER?"}" | base"{,"NUMBER"}"

%ignore /\s+/
%import common.LETTER
%import common.NUMBER
%import common.WORD

